###################################
# ServiceAccounts for workload identity
# Required for Istio AuthorizationPolicies
###################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: login-handler-sa
  namespace: workloads
  labels:
    app: login-handler-app
