###################################
# ServiceAccounts for workload identity
# Required for Istio AuthorizationPolicies
###################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: login-handler-sa
  namespace: workloads
  labels:
    app: login-handler-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospedajes-sa
  namespace: workloads
  labels:
    app: hospedajes-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::780522923809:role/travelhub-prod-hospedajes-sqs-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reservas-sa
  namespace: workloads
  labels:
    app: reservas-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::780522923809:role/travelhub-prod-reservas-sns-role
