apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-anomalias-deployment
  namespace: workloads
  labels:
    app: detector-anomalias-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector-anomalias-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: detector-anomalias-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - detector-anomalias-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: detector-anomalias
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/detectoranomaliasms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: detector-anomalias-ms-config
          - secretRef:
              name: detector-anomalias-ms-secret
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospedajes-deployment
  namespace: workloads
  labels:
    app: hospedajes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospedajes-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: hospedajes-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hospedajes-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      serviceAccountName: hospedajes-sa
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: hospedajesms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/hospedajesms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hospedajes-ms-config
          - secretRef:
              name: hospedajes-ms-secret
        ports:
        - containerPort: 8003
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-handler-deployment
  namespace: workloads
  labels:
    app: login-handler-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-handler-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: login-handler-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      serviceAccountName: login-handler-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - login-handler-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: loginhandlerms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/login-handler-ms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: login-handler-ms-config
          - secretRef:
              name: login-handler-ms-secret
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones-deployment
  namespace: workloads
  labels:
    app: notificaciones-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaciones-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: notificaciones-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - notificaciones-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      # notificaciones-ms has no database — remove init container
      containers:
      - name: notificacionesms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/notificacionesms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: notificaciones-ms-config
          - secretRef:
              name: notificaciones-ms-secret
        volumeMounts:
        - name: firebase-sa
          mountPath: /app/firebase-service-account.json
          subPath: firebase-service-account.json
          readOnly: true
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: firebase-sa
        secret:
          secretName: firebase-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-deployment
  namespace: workloads
  labels:
    app: reservas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: reservas-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - reservas-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      serviceAccountName: reservas-sa
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: reservasms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/reservasms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: reservas-ms-config
          - secretRef:
              name: reservas-ms-secret
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: workloads
  labels:
    app: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: users-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - users-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: users-ms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/usersms:latest
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: users-ms-config
            - secretRef:
                name: users-ms-secret
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-deployment
  namespace: workloads
  labels:
    app: pagos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: pagos-app
        version: v1
    spec:
      nodeSelector:
        role: workloads
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pagos-app
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine3.22
        env:
        - name: RDS_HOST
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_HOST
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: RDS_PORT
        command: ["sh", "-c", "until pg_isready -h $RDS_HOST -p $RDS_PORT -U postgres; do echo 'waiting for RDS...'; sleep 2; done"]
      containers:
      - name: pagosms
        image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/pagosms:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: pagos-ms-config
          - secretRef:
              name: pagos-ms-secret
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 1000
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
