apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospedajes-deployment
  labels:
    app: hospedajes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospedajes-app
  template:
    metadata:
      labels:
        app: hospedajes-app
        version: v1
    spec:
      containers:
      - name: hospedajesms
        image: hospedajesms:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: USERS_MS_URL
          value: "http://users-service"
        - name: POSTGRES_HOST
          value: "postgresdb-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3