apiVersion: v1
kind: Namespace
metadata:
  name: users-ms
---
# ── Secret ────────────────────────────────────────────────────────────────────
# In production use AWS Secrets Manager or Sealed Secrets instead of plaintext
apiVersion: v1
kind: Secret
metadata:
  name: users-ms-secret
  namespace: users-ms
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:SecurePass123!@travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com:5432/users_db"
---
# ── ConfigMap ─────────────────────────────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-ms-config
  namespace: users-ms
data:
  APP_NAME: "users_ms"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8004"
  LOGIN_HANDLER_MS_URL: "http://login-handler-ms.login-handler-ms.svc.cluster.local:8001"
---
# ── Deployment ────────────────────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
  namespace: users-ms
  labels:
    app: users-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com -p 5432 -U postgres; do
                echo "Waiting for RDS..."; sleep 3
              done
              echo "RDS ready!"
      containers:
        - name: users-ms
          image: 780522923809.dkr.ecr.us-east-1.amazonaws.com/travelhub/users-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: users-ms-config
            - secretRef:
                name: users-ms-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# ── Service ───────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: users-ms
  namespace: users-ms
spec:
  selector:
    app: users-ms
  ports:
    - port: 8004
      targetPort: 8004
