apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config
  namespace: workloads
data:
  RDS_HOST: "travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com"
  RDS_PORT: "5432"
---
# ── login-handler-ms ──────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: login-handler-ms-secret
  namespace: workloads
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:SecurePass123!@travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com:5432/auth_db"
  JWT_SECRET_KEY: "secure_secret_api"
  INTERNAL_API_KEY: "secure_internal_api"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: login-handler-ms-config
  namespace: workloads
data:
  APP_NAME: "login_handler_ms"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
---
# ── hospedajes-ms ─────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: hospedajes-ms-secret
  namespace: workloads
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:SecurePass123!@travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com:5432/hospedajes_db"
  JWT_SECRET_KEY: "secure_secret_api"
  INTERNAL_API_KEY: "secure_internal_api"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hospedajes-ms-config
  namespace: workloads
data:
  APP_NAME: "hospedajes_ms"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8003"
  JWT_ALGORITHM: "HS256"
  USERS_MS_URL: "http://users-service"
  RESERVAS_MS_URL: "http://reservas-service"
  AWS_REGION: "us-east-1"
  S3_BUCKET: "travelhub-images-780522923809"
---
# ── users-ms ──────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: users-ms-secret
  namespace: workloads
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:SecurePass123!@travelhub-prod-postgres.ci3w0yecas02.us-east-1.rds.amazonaws.com:5432/users_db"
  INTERNAL_API_KEY: "secure_internal_api"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-ms-config
  namespace: workloads
data:
  APP_NAME: "users_ms"
  APP_VERSION: "0.1.0"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOGIN_HANDLER_MS_URL: "http://login-handler-service"
